const Product = require('../models/Product');

// ── Slug utility ──────────────────────────────────────────────────
const slugify = (text = '') =>
  text.toString()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase().trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');

const getProducts = async (req, res) => {
  try {
    const products = await Product.find();
    res.json(products);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

/**
 * Lookup by slug first, fall back to MongoDB ObjectId.
 * This ensures old links (ID-based) still work during transition.
 */
const getProductById = async (req, res) => {
  try {
    const { id } = req.params; // could be a slug or an ObjectId
    let product;

    // Try slug lookup first
    product = await Product.findOne({ slug: id });

    // Fall back to ObjectId if it looks like one
    if (!product && /^[a-f\d]{24}$/i.test(id)) {
      product = await Product.findById(id);
    }

    if (!product) return res.status(404).json({ message: 'Produit non trouvé' });
    res.json(product);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

const createProduct = async (req, res) => {
  try {
    // Slug will be auto-generated by the pre('save') hook
    const product = new Product(req.body);
    await product.save();
    res.status(201).json(product);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

const updateProduct = async (req, res) => {
  try {
    const product = await Product.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
    res.json(product);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

const deleteProduct = async (req, res) => {
  try {
    await Product.findByIdAndDelete(req.params.id);
    res.json({ message: 'Product deleted' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

/**
 * Migration utility: backfill slugs for existing products that have none.
 * Called once on server start if needed.
 */
const backfillSlugs = async () => {
  try {
    const products = await Product.find({ slug: { $exists: false } });
    if (products.length === 0) return;

    console.log(`[SEO] Backfilling slugs for ${products.length} products...`);
    for (const product of products) {
      const base = slugify(product.name);
      let slug = base;
      let counter = 1;
      while (await Product.exists({ slug, _id: { $ne: product._id } })) {
        slug = `${base}-${counter++}`;
      }
      await Product.updateOne({ _id: product._id }, { slug });
    }
    console.log('[SEO] Slug backfill complete.');
  } catch (err) {
    console.error('[SEO] Slug backfill failed:', err.message);
  }
};

module.exports = { getProducts, getProductById, createProduct, updateProduct, deleteProduct, backfillSlugs };
